---
#------------------------------------------------------------------------------
# SYSTEM SETTINGS
#------------------------------------------------------------------------------

- name: Setting timezone to America/Los_Angeles
  ansible.builtin.timezone:
    name: "{{timezone}}"
  become: true

#------------------------------------------------------------------------------
# DISTRO SPECIFIC SETTINGS
#------------------------------------------------------------------------------

###############
### YUM/DNF ###
###############

- name: Installing MinIO dependencies for yum
  ansible.builtin.yum:
    name:
      - yum-utils
      - gpg-agent
      - curl
      - jq
      - tree
      - mlocate
      - tzdata
      - chrony
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'yum'

- name: Enable chrony service
  ansible.builtin.systemd:
    name: chronyd
    enabled: true
  become: true
  when: ansible_pkg_mgr == 'yum'

- name: Start chrony service
  ansible.builtin.systemd:
    name: chronyd
    state: started
  become: true
  when: ansible_pkg_mgr == 'yum'

###############
###   APT   ###
###############

- name: Installing MinIO dependencies for apt
  ansible.builtin.apt:
    name:
      - gpg-agent
      - curl
      - jq
      - tree
      - mlocate
      - tzdata
      - chrony
      - xfsprogs
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Enable chrony service
  ansible.builtin.systemd:
    name: chrony
    enabled: true
  become: true
  when: ansible_pkg_mgr == 'apt'

- name: Start chrony service
  ansible.builtin.systemd:
    name: chrony
    state: started
  become: true
  when: ansible_pkg_mgr == 'apt'

