---

###############
### YUM/DNF ###
###############
- name: Installing MinIO Linux dependencies for yum or dnf
  ansible.builtin.yum:
    name:
      - yum-utils
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: Install MinIO RPM package
  ansible.builtin.yum:
    name: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.rpm
    state: present
    update_cache: true
  become: true
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

###############
###   APT   ###
###############

- name: Installing MinIO dependencies for apt
  ansible.builtin.apt:
    name:
      - gpg-agent
      - curl
      - jq
      - tree
      - mlocate
      - tzdata
      - chrony
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

### CHRONY Setup
- name: Setting timezone to America/Los_Angeles
  ansible.builtin.timezone:
    name: America/Los_Angeles
  become: true

- name: Enable chrony service
  ansible.builtin.systemd:
    name: chrony
    enabled: true
  become: true

- name: Start chrony service
  ansible.builtin.systemd:
    name: chrony
    state: started
  become: true

### MinIO Binary Install
- name: Download MinIO Server Binary
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: "{{ minio_install_directory }}/minio"
    mode: '0755'
  become: true

- name: Download MinIO Command Line Client
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: "{{ minio_install_directory }}/mc"
    mode: '0755'
  become: true

- name: Create minio-user group
  ansible.builtin.group:
    name: "{{ minio_group }}"
    system: true

- name: Create minio-user user
  ansible.builtin.user:
    name: "{{ minio_user }}"
    home: "/home/{{ minio_user }}"
    group: "{{ minio_user }}"
    system: true
    create_home: true
