---

###############
### YUM/DNF ###
###############
- name: Installing MinIO Linux dependencies for yum or dnf
  ansible.builtin.yum:
    name:
      - yum-utils
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: Install MinIO RPM package
  ansible.builtin.yum:
    name: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.rpm
    state: present
    update_cache: true
  become: true
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

###############
###   APT   ###
###############

- name: Installing MinIO dependencies for apt
  ansible.builtin.apt:
    name:
      - gpg-agent
      - curl
    state: present
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: Download MinIO Debian package
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.deb
    dest: /tmp/minio.deb

- name: Install MinIO Debian package
  become: true
  ansible.builtin.apt:
    deb: /tmp/minio.deb
    state: present
    update_cache: yes