---
- name: Install MinIO Node Prerequisites
  ansible.builtin.include_tasks: 00-minio-node-prereqs.yaml

- name: Verify MinIO Node's Disk Configuration
  ansible.builtin.include_tasks: 01-minio-disk-configuration.yaml

- name: Provision The MinIO Binary
  ansible.builtin.include_tasks: 02-minio-binary-install.yaml

- name: Configuring MinIO system
  ansible.builtin.include_tasks: 03-minio-defaults-and-tls-config.yaml
